CREATE TABLE IF NOT EXISTS user(
   uno INT(4) PRIMARY KEY AUTO_INCREMENT
  ,name VARCHAR(30) NOT NULL
  ,pwd VARCHAR(50) NOT NULL
  ,birthday DATETIME
  ,sex enum('男','女')
  ,idcard CHAR(18) UNIQUE
  ,phone VARCHAR(20) UNIQUE
  ,intro VARCHAR(100)
  ,title VARCHAR(30)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS role(
   rno INT(2) PRIMARY KEY AUTO_INCREMENT
  ,name VARCHAR(30) NOT NULL
  ,intro VARCHAR(100)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS role_user(
   uno INT(4)
  ,rno INT(2)
  ,FOREIGN KEY (uno) REFERENCES user(uno)
  ,FOREIGN KEY (rno) REFERENCES role(rno)
  ,PRIMARY KEY (uno,rno)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS department(
   dno INT(4) PRIMARY KEY AUTO_INCREMENT
  ,name VARCHAR(30) NOT NULL
  ,detail VARCHAR(100)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS depar_user(
   uno INT(4)
  ,dno INT(4)
  ,FOREIGN KEY (uno) REFERENCES user(uno)
  ,FOREIGN KEY (dno) REFERENCES department(dno)
  ,PRIMARY KEY (uno,dno)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS shift(
   sno INT(4) PRIMARY KEY AUTO_INCREMENT
  ,start_date DATETIME NOT NULL
  ,end_date DATETIME NOT NULL
  ,dno INT(4)
  ,uno INT(4)
  ,max_num INT(2)
  ,num INT(2) DEFAULT 0
  ,detail VARCHAR(50)
  ,FOREIGN KEY (dno) REFERENCES department(dno)
  ,FOREIGN KEY (uno) REFERENCES user(uno)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS registration(
   sno INT(4)
  ,uno INT(4)
  ,FOREIGN KEY (sno) REFERENCES shift(sno)
  ,FOREIGN KEY (uno) REFERENCES user(uno)
  ,PRIMARY KEY (sno,uno)
)ENGINE =InnoDB DEFAULT CHARSET = UTF8;


